# Generated by Django 4.1.6 on 2023-02-03 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transitions", models.JSONField()),
                ("date", models.DateField(auto_now_add=True)),
                ("valid", models.BooleanField(default=True)),
                ("players", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
